"""init

Revision ID: 61ffa83de6e8
Revises: 4fc7a9ad8614
Create Date: 2025-06-02 10:04:06.442509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ffa83de6e8'
down_revision = '4fc7a9ad8614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
